import { WHO_REFS } from "../mockData";

function transformApiCandidate(c) {
  /* Handle both the detailed per-candidate shape and the TargetResult shape from /api/results */
  const sc = c.selected_candidate;
  if (sc) {
    /* TargetResult shape from /api/results/{job_id} */
    const parts = (c.mutation || "").match(/^([A-Za-z*-]*)(\d+)([A-Za-z*-]*)$/);
    return {
      gene: c.gene, ref: parts?.[1] || "", pos: parts ? parseInt(parts[2]) : 0, alt: parts?.[3] || "",
      drug: c.drug, drugFull: c.drug || "", conf: "", tier: "",
      label: c.label, strategy: c.detection_strategy === "direct" ? "Direct" : "Proximity",
      spacer: sc.spacer_seq, wtSpacer: sc.wt_spacer_seq || "", pam: sc.pam_seq,
      pamVariant: sc.pam_variant || "", pamPenalty: sc.pam_penalty ?? null, isCanonicalPam: sc.is_canonical_pam ?? null,
      score: sc.composite_score, disc: +(sc.discrimination_ratio || 0).toFixed(1), gc: sc.gc_content,
      discrimination: sc.discrimination || null, discMethod: sc.disc_method || null,
      neuralDisc: sc.neural_disc ?? null, featureDisc: sc.feature_disc ?? null,
      cnnScore: sc.cnn_score ?? null,
      cnnCalibrated: sc.cnn_calibrated ?? null,
      pamAdjusted: (sc.cnn_calibrated != null && sc.pam_penalty != null) ? +(sc.cnn_calibrated * sc.pam_penalty).toFixed(4) : sc.cnn_calibrated ?? null,
      activityQc: sc.activity_qc ?? null, discriminationQc: sc.discrimination_qc ?? null,
      mismatchTypeScore: sc.mismatch_type_score ?? null, flankingGcScore: sc.flanking_gc_score ?? null,
      mlScores: sc.ml_scores || [],
      ot: 0, hasPrimers: c.has_primers, hasSM: c.has_sm || false,
      smSpacer: c.sm_enhanced_spacer || null, smPosition: c.sm_position || null,
      smOriginalBase: c.sm_original_base || null, smReplacementBase: c.sm_replacement_base || null,
      fwd: c.fwd_primer, rev: c.rev_primer, amplicon: c.amplicon_length,
      proximityDistance: c.proximity_distance || null,
      mutActivity: sc.discrimination?.mut_activity || 0, wtActivity: sc.discrimination?.wt_activity || 0,
      asrpaDiscrimination: c.asrpa_discrimination || null,
      refs: WHO_REFS[c.label] || null,
      scoringBreakdown: null,
      isControl: false,
      readinessScore: c.readiness_score ?? null,
      readinessComponents: c.readiness_components ?? null,
      experimentalPriority: c.experimental_priority ?? null,
      riskProfile: c.risk_profile ?? null,
      priorityReason: c.priority_reason ?? null,
      // Phase 1; newly exposed backend fields
      seedPositionScore: sc.seed_position_score ?? null,
      gcPenalty: sc.gc_penalty ?? null,
      structurePenalty: sc.structure_penalty ?? null,
      homopolymerPenalty: sc.homopolymer_penalty ?? null,
      offtargetPenalty: sc.offtarget_penalty ?? null,
      proximityBonus: sc.proximity_bonus ?? null,
      mfe: sc.mfe ?? null,
      thermoDdg: sc.thermo_ddg ?? null,
      cumulativeDg: sc.cumulative_dg ?? null,
      localDg: sc.local_dg ?? null,
      pamDisrupted: sc.pam_disrupted ?? null,
      pamDisruptionType: sc.pam_disruption_type ?? null,
      offtargetHits: sc.offtarget_hits ?? null,
      offtargetIsClean: sc.offtarget_is_clean ?? null,
      discConfidence: sc.disc_confidence ?? null,
      discFeatureVector: sc.disc_feature_vector ?? null,
      discModelName: sc.disc_model_name ?? null,
      mlConfidence: sc.ml_confidence ?? null,
      mismatchType: sc.mismatch_type ?? null,
      refBaseAtMutation: sc.ref_base_at_mutation ?? null,
      fwdTm: c.fwd_tm ?? null, revTm: c.rev_tm ?? null,
      fwdGc: c.fwd_gc ?? null, revGc: c.rev_gc ?? null,
      primerDimerDg: c.primer_dimer_dg ?? null,
      ampliconSeq: c.amplicon_seq ?? null,
      locusGroup: c.locus_group ?? null,
      sharedAmpliconTargets: c.shared_amplicon_targets ?? null,
      asrpaFwd: c.asrpa_fwd ?? null,
      asrpaRev: c.asrpa_rev ?? null,
      asrpaAmpliconLength: c.asrpa_amplicon_length ?? null,
      sharedLocusWithAsrpa: c.shared_locus_with_asrpa ?? false,
    };
  }
  /* Original detailed per-candidate shape */
  return {
    gene: c.gene, ref: c.ref_aa, pos: c.position, alt: c.alt_aa,
    drug: c.drug, drugFull: c.drug_full, conf: c.who_confidence, tier: c.tier,
    label: c.target_label, strategy: c.detection_strategy === "direct" ? "Direct" : "Proximity",
    spacer: c.spacer_seq, wtSpacer: c.wt_spacer_seq, pam: c.pam_seq,
    pamVariant: c.pam_variant || "", pamPenalty: c.pam_penalty ?? null, isCanonicalPam: c.is_canonical_pam ?? null,
    score: c.score, disc: +(c.discrimination?.ratio || 0).toFixed(1), gc: c.gc_content,
    discrimination: c.discrimination || null,
    cnnScore: c.cnn_score ?? null,
    cnnCalibrated: c.cnn_calibrated ?? null,
    pamAdjusted: (c.cnn_calibrated != null && c.pam_penalty != null) ? +(c.cnn_calibrated * c.pam_penalty).toFixed(4) : c.cnn_calibrated ?? null,
    activityQc: c.activity_qc ?? null, discriminationQc: c.discrimination_qc ?? null,
    mismatchTypeScore: c.mismatch_type_score ?? null, flankingGcScore: c.flanking_gc_score ?? null,
    mlScores: c.ml_scores || [],
    ot: c.offtarget_count, hasPrimers: c.has_primers, hasSM: c.has_sm,
    smSpacer: c.sm_enhanced_spacer || null, smPosition: c.sm_position || null,
    smOriginalBase: c.sm_original_base || null, smReplacementBase: c.sm_replacement_base || null,
    fwd: c.fwd_primer, rev: c.rev_primer, amplicon: c.amplicon_length,
    proximityDistance: c.proximity_distance || null,
    mutActivity: c.discrimination?.mut_activity || 0,
    wtActivity: c.discrimination?.wt_activity || 0,
    asrpaDiscrimination: c.asrpa_discrimination || null,
    refs: WHO_REFS[c.target_label] || null,
    scoringBreakdown: c.scoring_breakdown || null,
    isControl: c.is_control || false,
    locusGroup: c.locus_group ?? null,
    sharedAmpliconTargets: c.shared_amplicon_targets ?? null,
    asrpaFwd: c.asrpa_fwd ?? null,
    asrpaRev: c.asrpa_rev ?? null,
    asrpaAmpliconLength: c.asrpa_amplicon_length ?? null,
    sharedLocusWithAsrpa: c.shared_locus_with_asrpa ?? false,
  };
}

export { transformApiCandidate };
